# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mULy-bNduQEvxTmWr6rZ9Lvc4bPoSqiP
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import requests

st.set_page_config(
    page_title="Dashboard Epidemiológico da AIDS",
    layout="wide"
)

st.title("Dashboard Epidemiológico da AIDS")

#lendo os dados
@st.cache_data
def carregar_dados():
    sexo = pd.read_csv("sexo.csv")
    raca = pd.read_csv("raça_cor.csv")
    idade = pd.read_csv("idade.csv")
    escolaridade = pd.read_csv("escolaridade.csv")
    ano = pd.read_csv("ano.csv")

    return sexo, raca, idade, escolaridade, ano


sexo, raca, idade, escolaridade, ano = carregar_dados()

#filtro
def aplicar_filtros(df, regiao, uf, municipio):

    df_filtrado = df.copy()

    if regiao != "Todas":
        df_filtrado = df_filtrado[
            df_filtrado["regiao"] == regiao
        ]

    if uf != "Todas":
        df_filtrado = df_filtrado[
            df_filtrado["uf"] == uf
        ]

    if municipio != "Todos":
        df_filtrado = df_filtrado[
            df_filtrado["municipio"] == municipio
        ]

    return df_filtrado

#filtros
col1, col2, col3 = st.columns(3)

#casos por região
with col1:

    regioes = sorted(
        sexo["regiao"]
        .dropna()
        .unique()
        .tolist()
    )

    regiao = st.selectbox(
        "Região",
        ["Todas"] + regioes
    )

#casos por estado
if regiao == "Todas":
    df_regiao = sexo.copy()

else:
    df_regiao = sexo[
        sexo["regiao"] == regiao
    ]

with col2:

    ufs = sorted(
        df_regiao["uf"]
        .dropna()
        .unique()
        .tolist()
    )

    uf = st.selectbox(
        "UF",
        ["Todas"] + ufs
    )

#casos por cidade
if uf == "Todas":
    df_uf = df_regiao.copy()

else:
    df_uf = df_regiao[
        df_regiao["uf"] == uf
    ]

with col3:

    municipios = sorted(
        df_uf["municipio"]
        .dropna()
        .unique()
        .tolist()
    )

    municipio = st.selectbox(
        "Município",
        ["Todos"] + municipios
    )

#aplicando os filtros em todos os gráficos
sexo_filtrado = aplicar_filtros(
    sexo,
    regiao,
    uf,
    municipio
)

raca_filtrado = aplicar_filtros(
    raca,
    regiao,
    uf,
    municipio
)

idade_filtrado = aplicar_filtros(
    idade,
    regiao,
    uf,
    municipio
)

escolaridade_filtrado = aplicar_filtros(
    escolaridade,
    regiao,
    uf,
    municipio
)

ano_filtrado = aplicar_filtros(
    ano,
    regiao,
    uf,
    municipio
)

#indicadores
total_casos = (
    sexo_filtrado["Masculino"].fillna(0).sum()
    +
    sexo_filtrado["Feminino"].fillna(0).sum()
)

masculino = (
    sexo_filtrado["Masculino"]
    .fillna(0)
    .sum()
)

feminino = (
    sexo_filtrado["Feminino"]
    .fillna(0)
    .sum()
)

c1, c2, c3 = st.columns(3)

c1.metric(
    "Total de Casos",
    f"{int(total_casos):,}"
)

c2.metric(
    "Masculino",
    f"{int(masculino):,}"
)

c3.metric(
    "Feminino",
    f"{int(feminino):,}"
)

st.divider()

#casos por ano
anos = [
    str(a)
    for a in range(2015, 2026)
]

serie_anos = {}

for coluna in anos:

    if coluna in ano_filtrado.columns:

        serie_anos[coluna] = (
            ano_filtrado[coluna]
            .fillna(0)
            .sum()
        )

df_anos = pd.DataFrame({
    "Ano": list(serie_anos.keys()),
    "Casos": list(serie_anos.values())
})

fig_ano = px.line(
    df_anos,
    x="Ano",
    y="Casos",
    markers=True,
    title="Casos por Ano"
)

st.plotly_chart(
    fig_ano,
    use_container_width=True
)

#casos por sexo
sexo_df = pd.DataFrame({
    "Sexo": [
        "Masculino",
        "Feminino"
    ],
    "Casos": [
        masculino,
        feminino
    ]
})

fig_sexo = px.pie(
    sexo_df,
    names="Sexo",
    values="Casos",
    title="Distribuição por Sexo"
)

#casos por raca/cor
racas = [
    "Branca",
    "Preta",
    "Amarela",
    "Parda",
    "Indígena"
]

dados_raca = []

for r in racas:

    if r in raca_filtrado.columns:

        dados_raca.append([
            r,
            raca_filtrado[r]
            .fillna(0)
            .sum()
        ])

df_raca = pd.DataFrame(
    dados_raca,
    columns=[
        "Raça",
        "Casos"
    ]
)

fig_raca = px.bar(
    df_raca,
    x="Raça",
    y="Casos",
    title="Distribuição por Raça/Cor"
)

col1, col2 = st.columns(2)

with col1:
    st.plotly_chart(
        fig_sexo,
        use_container_width=True
    )

with col2:
    st.plotly_chart(
        fig_raca,
        use_container_width=True
    )

#casos por idade
faixas = [
    "< 1 ano",
    "1-4",
    "5-9",
    "10-14",
    "15-19",
    "20-29",
    "30-39",
    "40-49",
    "50-59",
    "60-69",
    "70-79",
    "80 e mais"
]

idade_dados = []

for faixa in faixas:

    if faixa in idade_filtrado.columns:

        idade_dados.append([
            faixa,
            idade_filtrado[faixa]
            .fillna(0)
            .sum()
        ])

df_idade = pd.DataFrame(
    idade_dados,
    columns=[
        "Faixa Etária",
        "Casos"
    ]
)

fig_idade = px.bar(
    df_idade,
    x="Faixa Etária",
    y="Casos",
    title="Distribuição por Faixa Etária"
)

st.plotly_chart(
    fig_idade,
    use_container_width=True
)

#casos por escolaridade
esc_cols = [
    "analfabeto",
    "1ª a 4ª série incompleta",
    "4ª série completa",
    "5ª a 8ª série incompleta",
    "fundamental completo",
    "médio incompleto",
    "médio completo",
    "superior incompleto",
    "superior completo"
]

esc_dados = []

for coluna in esc_cols:

    if coluna in escolaridade_filtrado.columns:

        esc_dados.append([
            coluna,
            escolaridade_filtrado[coluna]
            .fillna(0)
            .sum()
        ])

df_esc = pd.DataFrame(
    esc_dados,
    columns=[
        "Escolaridade",
        "Casos"
    ]
)

fig_esc = px.bar(
    df_esc,
    x="Escolaridade",
    y="Casos",
    title="Distribuição por Escolaridade"
)

st.plotly_chart(
    fig_esc,
    use_container_width=True
)

#mapa de calor
st.subheader("Mapa de calor")

if uf == "Todas":

    dados_mapa = (
        sexo_filtrado
        .groupby("uf")[["Masculino", "Feminino"]]
        .sum()
        .reset_index()
    )

    dados_mapa["casos"] = (
        dados_mapa["Masculino"]
        +
        dados_mapa["Feminino"]
    )

    geojson_url = (
        "https://raw.githubusercontent.com/"
        "codeforamerica/click_that_hood/master/"
        "public/data/brazil-states.geojson"
    )

    geojson = requests.get(
        geojson_url
    ).json()

    fig_mapa = px.choropleth(
        dados_mapa,
        geojson=geojson,
        locations="uf",
        featureidkey="properties.sigla",
        color="casos",
        hover_name="uf",
        color_continuous_scale="Reds",
        title="Casos por Estado"
    )

    fig_mapa.update_geos(
        fitbounds="locations",
        visible=False
    )

    st.plotly_chart(
        fig_mapa,
        use_container_width=True
    )

else:

    dados_municipios = (
        sexo_filtrado
        .groupby("municipio")[["Masculino", "Feminino"]]
        .sum()
        .reset_index()
    )

    dados_municipios["casos"] = (
        dados_municipios["Masculino"]
        +
        dados_municipios["Feminino"]
    )

    fig = px.bar(
        dados_municipios.sort_values(
            "casos",
            ascending=False
        ),
        x="municipio",
        y="casos",
        title=f"Casos por Município ({uf})"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )