# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mULy-bNduQEvxTmWr6rZ9Lvc4bPoSqiP
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import requests
import sqlite3
import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_experimental.agents import create_pandas_dataframe_agent

load_dotenv()

st.set_page_config(
    page_title="Dashboard Epidemiológico da AIDS",
    layout="wide"
)

st.title("Dashboard Epidemiológico da AIDS")

#carregando os dados
@st.cache_data
def carregar_dados():
    db_path = os.path.join(os.path.dirname(__file__), "..", "data", "database.sqlite")
    conn = sqlite3.connect(db_path)
    
    def load_and_pivot(table_name):
        df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
        df_pivoted = df.pivot_table(
            index=['regiao', 'uf', 'cod_ibge', 'municipio', 'ano_diagnostico'],
            columns='categoria',
            values='quantidade',
            aggfunc='sum'
        ).reset_index()
        df_pivoted.columns.name = None
        return df_pivoted

    sexo = load_and_pivot("dados_sexo")
    raca = load_and_pivot("dados_raca_cor")
    idade = load_and_pivot("dados_idade")
    escolaridade = load_and_pivot("dados_escolaridade")
    ano = load_and_pivot("dados_ano")
    
    conn.close()
    return sexo, raca, idade, escolaridade, ano


sexo, raca, idade, escolaridade, ano = carregar_dados()

#filtros na sidebar
st.sidebar.header("Filtros")

# filtro região
regioes = sorted(
    sexo["regiao"]
    .dropna()
    .unique()
    .tolist()
)

regiao = st.sidebar.selectbox(
    "Região",
    ["Todas"] + regioes
)

# filtro uf
if regiao == "Todas":

    df_regiao = sexo.copy()

else:

    df_regiao = sexo[
        sexo["regiao"] == regiao
    ]

ufs = sorted(
    df_regiao["uf"]
    .dropna()
    .unique()
    .tolist()
)

uf = st.sidebar.selectbox(
    "UF",
    ["Todas"] + ufs
)

# filtro município
if uf == "Todas":

    df_uf = df_regiao.copy()

else:

    df_uf = df_regiao[
        df_regiao["uf"] == uf
    ]

municipios = sorted(
    df_uf["municipio"]
    .dropna()
    .unique()
    .tolist()
)

municipio = st.sidebar.selectbox(
    "Município",
    ["Todos"] + municipios
)

#aplicando os filtros
def aplicar_filtros(df, regiao, uf, municipio):

    df_filtrado = df.copy()

    if regiao != "Todas":

        df_filtrado = df_filtrado[
            df_filtrado["regiao"] == regiao
        ]

    if uf != "Todas":

        df_filtrado = df_filtrado[
            df_filtrado["uf"] == uf
        ]

    if municipio != "Todos":

        df_filtrado = df_filtrado[
            df_filtrado["municipio"] == municipio
        ]

    return df_filtrado

sexo_filtrado = aplicar_filtros(
    sexo,
    regiao,
    uf,
    municipio
)

raca_filtrado = aplicar_filtros(
    raca,
    regiao,
    uf,
    municipio
)

idade_filtrado = aplicar_filtros(
    idade,
    regiao,
    uf,
    municipio
)

escolaridade_filtrado = aplicar_filtros(
    escolaridade,
    regiao,
    uf,
    municipio
)

ano_filtrado = aplicar_filtros(
    ano,
    regiao,
    uf,
    municipio
)

#indicadores
total_casos = (
    sexo_filtrado["Masculino"].fillna(0).sum()
    +
    sexo_filtrado["Feminino"].fillna(0).sum()
)

masculino = (
    sexo_filtrado["Masculino"]
    .fillna(0)
    .sum()
)

feminino = (
    sexo_filtrado["Feminino"]
    .fillna(0)
    .sum()
)

c1, c2, c3 = st.columns(3)

c1.metric(
    "Total de Casos",
    f"{int(total_casos):,}"
)

c2.metric(
    "Masculino",
    f"{int(masculino):,}"
)

c3.metric(
    "Feminino",
    f"{int(feminino):,}"
)

st.divider()

#definindo abas
aba7, aba1, aba2, aba3, aba4, aba5, aba6 = st.tabs([
    "🤖 Chat Especialista",
    "📈 Casos por Ano",
    "👨‍👩‍👧 Casos por Sexo",
    "🎨 Casos por Raça/Cor",
    "📊 Casos por Faixa Etária",
    "🎓 Casos por Escolaridade",
    "🗺️ Mapa de Calor"
])

#aba 1 - casos por ano
with aba1:

    anos = [
        str(a)
        for a in range(2015, 2026)
    ]

    serie_anos = {}

    for coluna in anos:

        if coluna in ano_filtrado.columns:

            serie_anos[coluna] = (
                ano_filtrado[coluna]
                .fillna(0)
                .sum()
            )

    df_anos = pd.DataFrame({
        "Ano": list(serie_anos.keys()),
        "Casos": list(serie_anos.values())
    })

    fig_ano = px.line(
        df_anos,
        x="Ano",
        y="Casos",
        markers=True,
        title="Casos por Ano"
    )

    st.plotly_chart(
        fig_ano,
        use_container_width=True
    )

#aba 2 - casos por sexo
with aba2:

    sexo_df = pd.DataFrame({
        "Sexo": [
            "Masculino",
            "Feminino"
        ],
        "Casos": [
            masculino,
            feminino
        ]
    })

    fig_sexo = px.pie(
        sexo_df,
        names="Sexo",
        values="Casos",
        title="Distribuição por Sexo"
    )

    st.plotly_chart(
        fig_sexo,
        use_container_width=True
    )

#aba 3 - casos por cor
with aba3:

    racas = [
        "Branca",
        "Preta",
        "Amarela",
        "Parda",
        "Indígena"
    ]

    dados_raca = []

    for r in racas:

        if r in raca_filtrado.columns:

            dados_raca.append([
                r,
                raca_filtrado[r]
                .fillna(0)
                .sum()
            ])

    df_raca = pd.DataFrame(
        dados_raca,
        columns=[
            "Raça",
            "Casos"
        ]
    )

    fig_raca = px.bar(
        df_raca,
        x="Raça",
        y="Casos",
        title="Distribuição por Raça/Cor"
    )

    st.plotly_chart(
        fig_raca,
        use_container_width=True
    )

#aba 4 - casos por idade
with aba4:

    faixas = [
        "< 1 ano",
        "1-4",
        "5-9",
        "10-14",
        "15-19",
        "20-29",
        "30-39",
        "40-49",
        "50-59",
        "60-69",
        "70-79",
        "80 e mais"
    ]

    idade_dados = []

    for faixa in faixas:

        if faixa in idade_filtrado.columns:

            idade_dados.append([
                faixa,
                idade_filtrado[faixa]
                .fillna(0)
                .sum()
            ])

    df_idade = pd.DataFrame(
        idade_dados,
        columns=[
            "Faixa Etária",
            "Casos"
        ]
    )

    fig_idade = px.bar(
        df_idade,
        x="Faixa Etária",
        y="Casos",
        title="Distribuição por Faixa Etária"
    )

    st.plotly_chart(
        fig_idade,
        use_container_width=True
    )

#aba 5 - casos por escolaridade
with aba5:

    esc_cols = [
        "analfabeto",
        "1ª a 4ª série incompleta",
        "4ª série completa",
        "5ª a 8ª série incompleta",
        "fundamental completo",
        "médio incompleto",
        "médio completo",
        "superior incompleto",
        "superior completo"
    ]

    esc_dados = []

    for coluna in esc_cols:

        if coluna in escolaridade_filtrado.columns:

            esc_dados.append([
                coluna,
                escolaridade_filtrado[coluna]
                .fillna(0)
                .sum()
            ])

    df_esc = pd.DataFrame(
        esc_dados,
        columns=[
            "Escolaridade",
            "Casos"
        ]
    )

    fig_esc = px.bar(
        df_esc,
        x="Escolaridade",
        y="Casos",
        title="Distribuição por Escolaridade"
    )

    st.plotly_chart(
        fig_esc,
        use_container_width=True
    )

#mapa de calor
with aba6:

    st.subheader("Mapa de calor")

    if uf == "Todas":

        dados_mapa = (
            sexo_filtrado
            .groupby("uf")[["Masculino", "Feminino"]]
            .sum()
            .reset_index()
        )

        dados_mapa["casos"] = (
            dados_mapa["Masculino"]
            +
            dados_mapa["Feminino"]
        )

        geojson_url = (
            "https://raw.githubusercontent.com/"
            "codeforamerica/click_that_hood/master/"
            "public/data/brazil-states.geojson"
        )

        geojson = requests.get(
            geojson_url
        ).json()

        fig_mapa = px.choropleth(
            dados_mapa,
            geojson=geojson,
            locations="uf",
            featureidkey="properties.sigla",
            color="casos",
            hover_name="uf",
            color_continuous_scale="Reds",
            title="Casos por Estado"
        )

        fig_mapa.update_geos(
            fitbounds="locations",
            visible=False
        )

        st.plotly_chart(
            fig_mapa,
            use_container_width=True
        )

    else:

        dados_municipios = (
            sexo_filtrado
            .groupby("municipio")[["Masculino", "Feminino"]]
            .sum()
            .reset_index()
        )

        dados_municipios["casos"] = (
            dados_municipios["Masculino"]
            +
            dados_municipios["Feminino"]
        )

        fig = px.bar(
            dados_municipios.sort_values(
                "casos",
                ascending=False
            ),
            x="municipio",
            y="casos",
            title=f"Casos por Município ({uf})"
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

#aba 7 - chat especialista
with aba7:
    st.subheader("Chatbot Especialista em Dados")
    st.write("Faça perguntas em linguagem natural sobre os dados filtrados. A inteligência artificial vai analisar a tabela e te responder!")

    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Tenta st.secrets (Streamlit Cloud) primeiro, depois .env (local)
    api_key = st.secrets.get("GROQ_API_KEY", None) or os.getenv("GROQ_API_KEY")

    if not api_key:
        st.warning(" Chave da API do Groq não encontrada. Configure o arquivo .env com a variável GROQ_API_KEY.")
    else:
        prompt = st.chat_input("Ex: Quantos casos temos para pessoas indígenas?")

        if prompt:
            st.chat_message("user").markdown(prompt)
            st.session_state.messages.append({"role": "user", "content": prompt})

            llm = ChatGroq(model="llama-3.3-70b-versatile", api_key=api_key, temperature=0.0)

            try:
                PREFIX = """
Você é um analista de dados especialista em saúde.
Os 5 dataframes que você recebeu representam os dados filtrados de AIDS:
- df1: Casos por sexo
- df2: Casos por raça/cor
- df3: Casos por faixa etária
- df4: Casos por escolaridade
- df5: Casos por ano

Regras para suas respostas:
1. Responda de forma completa, explicativa e educada em português do Brasil.
2. NUNCA omita ou corte números. Se o número for decimal (com vírgula/ponto), mostre todas as casas decimais disponíveis ou formate com pelo menos 2 casas decimais (ex: 15,84 ou 1.250,50). Não retorne apenas o primeiro dígito de um número quebrado.
3. Certifique-se de realizar os cálculos corretamente nos dataframes antes de dar o resultado final.
"""
                # O allow_dangerous_code=True é necessário no langchain-experimental
                agent = create_pandas_dataframe_agent(
                    llm, 
                    [sexo_filtrado, raca_filtrado, idade_filtrado, escolaridade_filtrado, ano_filtrado],
                    verbose=True, 
                    allow_dangerous_code=True,
                    prefix=PREFIX,
                    max_iterations=4,
                    agent_executor_kwargs={"handle_parsing_errors": True}
                )
                
                with st.spinner("Analisando os dados..."):
                    resposta = agent.invoke(prompt)
                
                with st.chat_message("assistant"):
                    st.markdown(resposta["output"])
                
                st.session_state.messages.append({"role": "assistant", "content": resposta["output"]})
                
            except Exception as e:
                st.error(f"Erro ao processar a pergunta: {e}")